# Generated by Django 4.2.7 on 2024-01-23 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("datum", models.DateTimeField()),
                ("ticketAvailability", models.BooleanField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("artist", models.CharField(max_length=255)),
                (
                    "video_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("img_source", models.URLField(blank=True, null=True)),
                (
                    "categoryID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veranstaltung.category",
                    ),
                ),
            ],
            options={
                "ordering": ["datum"],
            },
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("standort", models.CharField(max_length=255)),
                ("seatingCapacity", models.IntegerField()),
                ("detail", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["location"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("birthday", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nickname"],
            },
        ),
        migrations.CreateModel(
            name="Warenkorb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.IntegerField(default=1)),
                ("sessionID", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "eventID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veranstaltung.event",
                    ),
                ),
                (
                    "myuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veranstaltung.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "eventID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veranstaltung.event",
                    ),
                ),
                (
                    "eventLocationID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="veranstaltung.eventlocation",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="veranstaltung.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["eventID"],
            },
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="userID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="veranstaltung.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="locationID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="veranstaltung.eventlocation",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="userID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="veranstaltung.userprofile",
            ),
        ),
    ]
